### ISSUE TITLE
hCaptcha seems to fail?

### ISSUE THREAD

**Issue by Mmalherbe** [Overmiind/Puppeteer-sharp-extra#34]
Hey!

I'm wondering if I did something wrong or if the captcha plugin isn't able to do hCaptcha.

I set it up with TwoCaptcha ( With API KEY of course).

`            var recaptchaPlugin = new RecaptchaPlugin(new TwoCaptcha("35cc0db466ebea493d132aca44b0e745"));
            extra.Use(recaptchaPlugin);
var browser = await extra.LaunchAsync(new LaunchOptions()
            {
                Headless = false,}

var captchaResult = recaptchaPlugin.SolveCaptchaAsync(page); 
`

Where the SolveCaptchaAsync throws an innerexception

**Comment by Mmalherbe** [comment]
`   at PuppeteerExtraSharp.Plugins.Recaptcha.Recaptcha.<GetKeyAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PuppeteerExtraSharp.Plugins.Recaptcha.Recaptcha.<Solve>d__3.MoveNext()`
   
   "Recaptcha key not found!" ( Sorry just found the actual exception)

**Comment by Overmiind** [comment]
Hi, Recaptcha plugin hasn't been updated for a long time. It is still able to solve V2 ReCaptcha, but doesn't support other versions of captcha. I saw that the original plugin was updated and now can solve a lot of captchas, so I will try to update c# plugin this weekend

**Comment by Mmalherbe** [comment]
> 

Awesome! 🤞

**Comment by Mmalherbe** [comment]
Merry xmas! 

Any chance you can give an ETA when it will be updated?

**Comment by Velka-DEV** [comment]
@Overmiind Hi buddy, there is any chances of seing the hcaptcha support soon or absolutly not ?

Thanks for your work

**Comment by Mmalherbe** [comment]
@Overmiind  Any update on if you'll do this? Or should I go check a diff plugin

**Comment by Overmiind** [comment]
Hi, I'm sorry to keep you waiting, I started to rewrite Recaptcha and Hcaptcha plugin about a month ago, but now a don't have enough time for this. I can't give you any prediction, I have almost done with Recaptcha, but I should also write Hcaptcha handler and tests.

**Comment by Mmalherbe** [comment]
> Hi, I'm sorry to keep you waiting, I started to rewrite Recaptcha and Hcaptcha plugin about a month ago, but now a don't have enough time for this. I can't give you any prediction, I have almost done with Recaptcha, but I should also write Hcaptcha handler and tests.

Awesome!

cant wait for the HCaptcha one 🤞
