### ISSUE TITLE
PuppeteerSharpV9 Cannot launch: Method not found ICDPSession.SendAsync

### ISSUE THREAD

**Issue by w4po** [Overmiind/Puppeteer-sharp-extra#48]
Hello @namilkimfree @Overmiind ,
I am using [NamIlKim's custom version](https://github.com/namilkimfree/Puppeteer-sharp-extra) It works just fine with V8.0.0
But It doesn't work with V9+

```
Method not found: 'System.Threading.Tasks.Task`1<Newtonsoft.Json.Linq.JObject> PuppeteerSharp.ICDPSession.SendAsync(System.String, System.Object, Boolean)'.

at PuppeteerExtraSharp.Plugins.ExtraStealth.Evasions.UserAgent.<OnPageCreated>d__3.MoveNext()
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
at PuppeteerExtraSharp.Plugins.ExtraStealth.Evasions.UserAgent.OnPageCreated(IPage page)
at PuppeteerExtraSharp.PuppeteerExtra.<Register>d__9.MoveNext()
at PuppeteerExtraSharp.PuppeteerExtra.<OnStart>d__5.MoveNext()
at PuppeteerExtraSharp.PuppeteerExtra.<LaunchAsync>d__2.MoveNext()
```

Thank you.

**Comment by namilkimfree** [comment]
Ok, I'll work on version 9.

**Comment by w4po** [comment]
Thank you,
I've cloned your repo and just updated the project file (PuppeteerExtraSharp.csproj) to use the 9.0.0 version instead of 8.0.0.
And it works just fine.

```
  <ItemGroup>
    <PackageReference Include="PuppeteerSharp" Version="9.0.0" />
    <PackageReference Include="RestSharp" Version="108.0.3" />
  </ItemGroup>
```

**Comment by namilkimfree** [comment]
@w4po  
update package version 1.3.9

check please

**Comment by Overmiind** [comment]
Fixed by [R3D4NG3L](https://github.com/Overmiind/Puppeteer-sharp-extra/pull/49)
Please update the NuGet package version of Puppeteer Extra Sharp to 2.0.
